name: Cargo Build & Test

on: [push]

env: 
  CARGO_TERM_COLOR: always

jobs:
  lint:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      
      - name: Update toolchain
        run: rustup update

      - name: Format
        run: cargo fmt -- --check

      - name: Clippy
        run: cargo clippy --verbose -- -D warnings
  
  build_and_test:
    strategy:
      matrix:
        os: 
          - ubuntu-latest
          - macos-latest
          - windows-latest
    runs-on: ${{ matrix.os }}

    steps:
      - uses: actions/checkout@v3
      
      - name: Update toolchain
        run: rustup update

      - name: Build
        run: cargo build --verbose
      
      - name: Test
        run: cargo test --verbose

  docs:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      
      - name: Update toolchain
        run: rustup update
      
      - name: Documentation
        run: cargo doc --verbose

      